### ISSUE TITLE
Can't use FlatList in HomeScreen

### ISSUE THREAD

**Issue by fedecaccia** [tassdr/react-native-template#2]
I'm trying to modify the homescreen script, and to add a flatlist instead of the welcome text. I'm updating the render section in HomeScreen.js with:

```
render() {
    return (
      // <View style={styless.container}>
      <FeedList />
      // </View>
      //   <Text>Hello! Welcome to my homepage</Text>
    );
  }
```

Donde FeedList is definied as a Component with a FlatList inside.
The rendered flatlist behavior is bad. I can not scroll it.

**Comment by tassdr** [comment]
Hello, 

Could you provide the code included in your FeedList component?
